version: "3.9"
services:
   shop:
    build: .
    environment:
     ADMINS: $ADMINS
     API_HASH: $API_HASH
     API_ID: $API_ID
     BOT_TOKEN: $BOT_TOKEN
     FSub_Channel: $FSub_Channel
     SESSION: $SESSION
     LOG_CHANNEL: $LOG_CHANNEL
